version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=srv881.hstgr.io
      - DB_USER=u660141438_app_factu
      - DB_PASSWORD=Colombia5@
      - DB_NAME=u660141438_app_facturas
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped