version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_development
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: